# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode


trigger:
  - master

pool:
  vmImage: 'macOS-10.15'

variables:
  scheme: 'iOSHelloWorld'
  sdk: 'iphoneos'
  configuration: 'Debug'

steps:
- task: ShellScript@2
  inputs:
    scriptPath: 'test.sh'
    #args: '' # Optional
    #disableAutoCwd: false # Optional
    #cwd: '' # Optional
    #failOnStandardError: false
  

- task: Xcode@5
  inputs:
    actions: 'test'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
    destinationTypeOption: simulators
    destinationSimulators: iPhone 11 Pro
    destinationPlatformOption: iOS
